apiVersion: apps/v1
kind: Deployment
metadata:
  name: myserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: myserver
          image: nginx
          ports:
            - containerPort: 80

