apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-svc
      port: 80
  selector:
    app: server #nome do labels app que ele vai buscar


